apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-iris-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-iris-app
  template:
    metadata:
      labels:
        app: flask-iris-app
    spec:
      containers:
      - name: flask-iris-container
        image: flask-iris-app:latest
        imagePullPolicy: IfNotPresent  # Ensures the image is not pulled from a registry
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-iris-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
  selector:
    app: flask-iris-app
